version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: stg_subscriptions
    columns:
      - name: subscription_id
        tests:
          - not_null
          - unique

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - not_null
          - unique
