version: 2

models:

  - name: dim_customer
    description: >
      Dimension table containing one record per customer.
    columns:
      - name: customer_id
        description: Unique identifier for customer.
        tests:
          - not_null
          - unique

      - name: customer_name
        description: Name of the customer.

      - name: signup_date
        description: Customer signup date.

      - name: country
        description: Customer country.

  - name: fact_subscription
    description: >
      Subscription-level fact table used for churn analysis.
    columns:
      - name: subscription_id
        description: Unique subscription identifier.
        tests:
          - not_null
          - unique

      - name: customer_id
        description: Customer identifier.
        tests:
          - not_null

      - name: status
        description: Subscription status.
        tests:
          - accepted_values:
              arguments:
                values: ['ACTIVE', 'CANCELLED']

      - name: is_churned
        description: Churn indicator flag.
        tests:
          - accepted_values:
              arguments:
                values: [0, 1]

  - name: fact_revenue_mrr
    description: >
      Monthly and annual recurring revenue metrics.
    columns:
      - name: revenue_month
        description: Revenue month.
        tests:
          - not_null

      - name: mrr
        description: Monthly recurring revenue.
        tests:
          - not_null

      - name: arr
        description: Annual recurring revenue.

  - name: fact_payment_health
    description: >
      Monthly payment success and failure metrics.
    columns:
      - name: payment_month
        description: Payment month.
        tests:
          - not_null

      - name: total_payments
        description: Total payment attempts.
        tests:
          - not_null

      - name: failure_rate_pct
        description: Payment failure percentage.
        tests:
          - not_null
